name: Update Version

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Get base branch version
        id: get_base_version
        run: echo "BASE_VERSION=$(grep mod_version gradle.properties | cut -d'=' -f2 | tr -d '[:space:]')" >> $GITHUB_ENV

      - name: Get merged branch version
        id: get_merged_version
        run: |
          git checkout ${{ github.event.before }}
          echo "MERGED_VERSION=$(grep mod_version gradle.properties | cut -d'=' -f2 | tr -d '[:space:]')" >> $GITHUB_ENV

      - name: Run version update script
        run: ./.github/scripts/versioning.sh $BASE_VERSION $MERGED_VERSION
        shell: bash

      - name: Commit and push changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git commit -am "Update version" || true
          git push
