name: Update Version

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed
jobs:
  update-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get mod version
        id: get_base_version
        run: echo "VERSION=$(grep mod_version gradle.properties | cut -d'=' -f2 | tr -d '[:space:]')" >> $GITHUB_ENV

      - name: Run version update script
        run: ./.github/scripts/versioning.sh $VERSION
        shell: bash

      - name: Commit and push changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "actions@github.com"
          git commit -am "Update version" || true
          git push
