name: Update Version on Merge

on:
  pull_request:
    types:
      - closed

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2

      - name: Get base branch version
        id: get_base_version
        run: echo "::set-output name=version::$(grep version gradle.properties | cut -d'=' -f2 | tr -d '[:space:]')"

      - name: Get merged branch version
        id: get_merged_version
        run: |
          git checkout ${{ github.event.before }}
          merged_version=$(grep version gradle.properties | cut -d'=' -f2 | tr -d '[:space:]')
          echo "::set-output name=version::${merged_version}"

      - name: Compare versions and update
        run: |
          base_version="${{ steps.get_base_version.outputs.version }}"
          merged_version="${{ steps.get_merged_version.outputs.version }}"

          if [[ "$base_version" == "$merged_version" ]]; then
            new_version=$((merged_version + 1))
            echo "Updating version to $new_version"
            sed -i "s/version=$merged_version/version=$new_version/" gradle.properties
          else
            echo "Merged version is greater, keeping it."
          fi

      - name: Commit and push changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git commit -am "Update version" || true
          git push
