name: Update Version on Merge

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          
      - name: Get base branch version
        id: get_base_version
        run: echo "::set-output name=version::$(grep version gradle.properties | cut -d'=' -f2 | tr -d '[:space:]')"

      - name: Get merged branch version
        id: get_merged_version
        run: |
          git checkout ${{ github.event.before }}
          merged_version=$(grep version gradle.properties | cut -d'=' -f2 | tr -d '[:space:]')
          echo "::set-output name=version::${merged_version}"

      - name: Run version update script
        run: ./.github/scripts/update_version.sh "${{ steps.get_base_version.outputs.version }}" "${{ steps.get_merged_version.outputs.version }}"
        shell: bash
        
      - name: Commit and push changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git commit -am "Update version" || true
          git push
